In [2]:
# Example of augumented assignment statements 

spam = 12

# spam = spam + 1

spam += 1

print(spam)

13


In [5]:
# Equivalent to spam = spam - 1

spam = 12

spam -= 1

print(spam)

11


In [6]:
# Equivalent to spam = spam * 1

spam = 12

spam *= 1

print(spam)

12


In [7]:
# Equivalent to spam = spam / 1

spam = 12

spam /= 1

print(spam)

12.0


In [8]:
# Equivalent to spam = spam % 1

spam = 12

spam %= 1

print(spam)

0


In [16]:
# Example of list and how to access the items within it. 

sales = [10, 12, 25, 6, 9, 8]

print(sales[1])

#Example of Index Error 

print(sales[9])

12


IndexError: list index out of range

In [17]:
# Example of len()

sales = [10, 12, 25, 6, 9, 8]

print(len(sales))

6


In [18]:
# Editing Lists 

# Example of removing values

sales = [10, 12, 25, 6, 9, 8]

del sales[4]

print(sales)

[10, 12, 25, 6, 8]


In [19]:
# Editing Lists 

# Example of removing values

sales = [10, 12, 25, 6, 9, 8]

sales.remove(10)

print(sales)

[12, 25, 6, 9, 8]


In [20]:
# Editing Lists 

# Example of removing values

sales = [10, 12, 25, 6, 9, 8]

sales.pop(4)

print(sales)

[10, 12, 25, 6, 8]


In [21]:
# Editing Lists 

# Example of add values

sales = [10, 12, 25, 6, 9, 8]

sales.insert(1,7)

print(sales)

[10, 7, 12, 25, 6, 9, 8]


In [22]:
# Editing Lists 

# Example of add values

sales = [10, 12, 25, 6, 9, 8]

sales.append(13)

print(sales)

[10, 12, 25, 6, 9, 8, 13]


In [24]:
# Example of slices

sales = [10, 12, 25, 6, 9, 8]

new_sales = sales[1:4]

print(new_sales)

[12, 25, 6]


In [25]:
# Example of sort and reverse 

sales.sort()

print(sales)

[6, 8, 9, 10, 12, 25]


In [26]:
# Example of sort and reverse 

sales.reverse()

print(sales)

[25, 12, 10, 9, 8, 6]


In [29]:
# Example of list concatenation and replication

sales = [10, 12, 25, 6, 9, 8]

new_data = [11, 8, 7]

sales = sales + new_data

print(sales)

[10, 12, 25, 6, 9, 8, 11, 8, 7]


In [33]:
# Example of list concatenation and replication

sales = [10, 12, 25, 6, 9, 8]

new_sales = sales*5

print(new_sales)

[10, 12, 25, 6, 9, 8, 10, 12, 25, 6, 9, 8, 10, 12, 25, 6, 9, 8, 10, 12, 25, 6, 9, 8, 10, 12, 25, 6, 9, 8]


In [34]:
# Example with In and Not In Operators 

sales = [10, 12, 25, 6, 9, 8]

print(10 in sales)

True


In [35]:
sales = [10, 12, 25, 6, 9, 8]

print(11 not in sales)

True


In [36]:
# Example of Using loops in lists 

sales = [10, 12, 25, 6, 9, 8]

total_sales = 0

for data in sales: 
    total_sales += data 
    
print(total_sales)

70


In [39]:
# Multiple assignment trick

sales = [10, 12, 25, 6, 9, 8]

'''
employee_1 = sales[0]
employee_2 = sales[1]
employee_3 = sales[2]
employee_4 = sales[3]
employee_5 = sales[4]
employee_6 = sales[5]
'''

employee_1, employee_2, employee_3, employee_4, employee_5, employee_6 = sales

print(employee_5)

9


In [42]:
# Example of list functions 

sales = [10, 12, 25, 6, 9, 8]

for index,value in enumerate(sales):
    print('Sales at index '  + str(index) + ' is ' + str(value))


Sales at index 0 is 10
Sales at index 1 is 12
Sales at index 2 is 25
Sales at index 3 is 6
Sales at index 4 is 9
Sales at index 5 is 8


In [43]:
# Example of list functions 

import random 

sales = [10, 12, 25, 6, 9, 8]

print(random.choice(sales))


6


In [44]:
import random 

sales = [10, 12, 25, 6, 9, 8]

random.shuffle(sales)

print(sales)

[6, 8, 12, 10, 25, 9]


In [48]:
# Example of passing references in lists 

# Issues faced when passing on lists

sales = [10, 12, 25, 6, 9, 8]

data = sales 

print(data)

data.append(6)

print(data)
print(sales)

[10, 12, 25, 6, 9, 8]
[10, 12, 25, 6, 9, 8, 6]
[10, 12, 25, 6, 9, 8, 6]


In [49]:
# Ways to fix passing on data

import copy 

sales = [10, 12, 25, 6, 9, 8]

data = copy.copy(sales)

data.append(6)

print(data)
print(sales)



[10, 12, 25, 6, 9, 8, 6]
[10, 12, 25, 6, 9, 8]


In [54]:
# Example of Tuples

sales = (10, 12, 25, 6, 9, 8)

sales_list = [10, 12, 25, 6, 9, 8]

sales_list[3] = 17

print(sales_list)

sales[3] = 17


[10, 12, 25, 17, 9, 8]


TypeError: 'tuple' object does not support item assignment

In [56]:
# Converting Types with the list () and tuple ()

sales = (10, 12, 25, 6, 9, 8)

sales = list(sales)

print(type(sales))


<class 'list'>


In [57]:
sales = [10, 12, 25, 6, 9, 8]

sales = tuple(sales)

print(type(sales))

<class 'tuple'>


# Dictionaries
 
# Like a list dictionary is a mutable collection of many values, but unlike indexes for lists, dictionaries can use many different types of data 


In [59]:
# Example of dictionary 

data = {'name':'Jack', 'age':42, 'country':'USA'}

print(type(data))

<class 'dict'>


In [61]:
# Example of keys ()

data = {'name':'Jack', 'age':42, 'country':'USA'}

for key in data.keys():
    print(key)

name
age
country


In [63]:
# Example of values in keys ()

data = {'name':'Jack', 'age':42, 'country':'USA'}

for value in data.values():
    print(value)

Jack
42
USA


In [65]:
# Example of items ()

data = {'name':'Jack', 'age':42, 'country':'USA'}

for key,value in data.items():
    print("Key:" + key + ',' + "Value:" + str(value))


Key:name,Value:Jack
Key:age,Value:42
Key:country,Value:USA


In [71]:
# Checking whether a key or an item exists in a dictionary

print('name' in data.keys())

# Example of get()

print("Name of the customer is " + data['name'] )

True
Name of the customer is Jack


In [74]:
# Checking whether a key or an item exists in a dictionary

print('name' in data.keys())

# Example of get()

print("Id of the customer is " + str(data.get('id',0)))

True
Id of the customer is 0


In [80]:
# Example of setdefault

print('id' in data.keys())

data.setdefault('id',100)

print("Id of the customer is " + str(data['id']))

True
Id of the customer is 100


In [84]:
# Example of nested dictionaries

database = {'Jack':{'age':42, 'gender':'male','purchases':30},'Jill':{'age':28, 'gender':'female','purchases ':10} }

In [85]:
print(database.keys())

dict_keys(['Jack', 'Jill'])


In [86]:
print(database['Jack']['age'])

42


In [87]:
ages = []

for key in database.keys():
    ages.append(database[key]['age'])
    
print(ages)

[42, 28]


# Week 3 - Arrays 

In [98]:
# Creating an array - from a list, linspace, arange 

import numpy as np

A = [1,2,3]

B = np.array(A)

print(type(B))

C = np.array([1,2,3])
print(type(C))

D = np.linspace(0,6,3)
print(D)

E = np.arange(0,10,2)
print(E)

# Creating a rank 2 array - linalg.matrix_rank

F = np.array([[1,2,3],[4,5,6]])

print(F)

print(np.linalg.matrix_rank(F))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[0. 3. 6.]
[0 2 4 6 8]
[[1 2 3]
 [4 5 6]]
2


In [99]:
# Creating an array of all zeros 

z = np.zeros((2,1))

print(z)

[[0.]
 [0.]]


In [101]:
# Create an array of all ones 

o = np.ones((3,4))

print(o)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [105]:
# Create a constant array 

c = np.full((2,4),10.24, dtype = int)

print(c)

[[10 10 10 10]
 [10 10 10 10]]


In [106]:
# Creating a 2x2 identity matrix 

I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [108]:
# Create an array filled with random values - random.random 

R = np.random.random((2,3))

print(R)

[[0.76992954 0.37975468 0.56366521]
 [0.22062104 0.03987629 0.38258927]]


In [110]:
# Create an array filled with random values - random.random 

RR = np.random.randint(10, size=(2,3))

print(RR)

[[2 6 0]
 [8 9 6]]


In [111]:
# Arrays are generated from lists
# Examples of using array methods 

data = [1,2,3]

data.append(4)

final_data = np.array(data)

print(final_data)

[1 2 3 4]


In [112]:
# Example of slicing arrays

A = np.array([0,1,2,3,4,5,6,7,8])

# first n elements 

B = A[:5]

print(B)

[0 1 2 3 4]


In [114]:
# elements after index 'n'

B =A[5:]

print(B)

[5 6 7 8]


In [115]:
# middle sub-array 

B =A[2:5]

print(B)

[2 3 4]


In [116]:
#every other element

B =A[::2]

print(B)

[0 2 4 6 8]


In [118]:
#every other element starting at index 1 

B =A[1::2]

print(B)

[1 3 5 7]


In [119]:
# All elements reversed 

B =A[::-1]

print(B)

[8 7 6 5 4 3 2 1 0]


In [120]:
# reverse every other value from index 5

B = A[5::-2]

print(B)

[5 3 1]


In [122]:
# Multi-dimensional sub-arrays 

np.random.seed(10)

S = np.random.randint(10, size = (4,4))

print(S)

[[9 4 0 1]
 [9 0 1 8]
 [9 0 8 6]
 [4 3 0 4]]


In [123]:
# Sub-array with rows and columns 

D = S[:2,:2]

print(D)

[[9 4]
 [9 0]]


In [125]:
#reverse

D = S[::-1,::-1]

print(D)

[[4 0 3 4]
 [6 8 0 9]
 [8 1 0 9]
 [1 0 4 9]]


In [126]:
# access first column

D = S[:,0]

print(D)

[9 9 9 4]


In [127]:
# access first row

D = S[0,:]

print(D)

[9 4 0 1]


In [130]:
# Example of editing array value 

print(S[2][2])

S[2][2] = 3

print(S[2][2])

8
3


In [134]:
# Example of array operations 

A = np.array([1,2,3])

B = np.array([10,20,30])

print(A+B)
print(A-B)
print(A*B)
print(A/B)
print(np.sqrt(B))


print(np.multiply(A,B))

[11 22 33]
[ -9 -18 -27]
[10 40 90]
[0.1 0.1 0.1]
[3.16227766 4.47213595 5.47722558]
[10 40 90]


In [137]:
# Example of using loops with arrays 

np.random.seed

S = np.random.randint(100, size = (5,5))

print(S)

for x in range(len(S)):
    for y in range(len(S[x])):
        print(" The value in row " + str(x)  + " and column " + str(y) + " is " + str(S[x][y]))



[[96 88 44  5  4]
 [71 88 88 50 54]
 [34 15 77 88 15]
 [ 6 85 22 11 12]
 [92 96 62 57 79]]
 The value in row 0 and column 0 is 96
 The value in row 0 and column 1 is 88
 The value in row 0 and column 2 is 44
 The value in row 0 and column 3 is 5
 The value in row 0 and column 4 is 4
 The value in row 1 and column 0 is 71
 The value in row 1 and column 1 is 88
 The value in row 1 and column 2 is 88
 The value in row 1 and column 3 is 50
 The value in row 1 and column 4 is 54
 The value in row 2 and column 0 is 34
 The value in row 2 and column 1 is 15
 The value in row 2 and column 2 is 77
 The value in row 2 and column 3 is 88
 The value in row 2 and column 4 is 15
 The value in row 3 and column 0 is 6
 The value in row 3 and column 1 is 85
 The value in row 3 and column 2 is 22
 The value in row 3 and column 3 is 11
 The value in row 3 and column 4 is 12
 The value in row 4 and column 0 is 92
 The value in row 4 and column 1 is 96
 The value in row 4 and column 2 is 62
 The value in r